use_frameworks!

platform :ios, '8.0'

target 'VXWMZBanner_Example' do
  pod 'VXWMZBanner', :path => '../'
  pod "SDWebImage"
  target 'VXWMZBanner_Tests' do
    inherit! :search_paths

    
  end
end
